server:
  port: 4141

spring:

  liquibase:
    enabled: true
    changeLog: "classpath:db/changelog/db.changelog-master.yaml"
    drop-first: ${SIMPLE_ERP_LIQUIBASE_ENABLE_DROP_FIRST:true}

  datasource:
    url: jdbc:mysql://${SIMPLE_ERP_DB_IP:localhost}:${SIMPLE_ERP_DB_PORT:3306}/simple_erp
    username: ${SIMPLE_ERP_DB_USERNAME:root}
    password: ${SIMPLE_ERP_DB_PASSWORD:root1234}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        format_sql: true
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
